-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "AIRLINES" (
    "AIRLINE_CODE" VARCHAR   NOT NULL,
    "AIRLINE" VARCHAR   NOT NULL,
    CONSTRAINT "pk_AIRLINES" PRIMARY KEY (
        "AIRLINE_CODE"
     )
);

CREATE TABLE "AIRPORTS" (
    "AIRPORT_CODE" VARCHAR   NOT NULL,
    "AIRPORT" VARCHAR   NOT NULL,
    "CITY" VARCHAR   NOT NULL,
    "STATE" VARCHAR   NOT NULL,
    "COUNTRY" VARCHAR   NOT NULL,
    "LATITUDE" INT   NOT NULL,
    "LONGITUDE" INT   NOT NULL,
    CONSTRAINT "pk_AIRPORTS" PRIMARY KEY (
        "AIRPORT_CODE"
     )
);

CREATE TABLE "MODFLIGHTS" (
    "FLIGHT_ID" INT   NOT NULL,
    "YEAR" INT   NOT NULL,
    "MONTH" INT   NOT NULL,
    "DAY" INT   NOT NULL,
    "DAY_OF_WEEK" INT   NOT NULL,
    "AIRLINE_CODE" VARCHAR   NOT NULL,
    "FLIGHT_NUMBER" INT   NOT NULL,
    "TAIL_NUMBER" VARCHAR   NOT NULL,
    "ORIGIN_AIRPORT_CODE" VARCHAR   NOT NULL,
    "DESTINATION_AIRORT_CODE" VARCHAR   NOT NULL,
    "SCHEDULED_DEPARTURE" INT   NOT NULL,
    "DEPARTURE_TIME" INT   NOT NULL,
    "DEPARTURE_DELAY" INT   NOT NULL,
    "TAXI_OUT" INT   NOT NULL,
    "WHEELS_OFF" INT   NOT NULL,
    "SCHEDULED_TIME" INT   NOT NULL,
    "ELAPSED_TIME" INT   NOT NULL,
    "AIR_TIME" INT   NOT NULL,
    "DISTANCE" INT   NOT NULL,
    "WHEELS_ON" INT   NOT NULL,
    "TAXI_IN" INT   NOT NULL,
    "SCHEDULED_ARRIVAL" INT   NOT NULL,
    "ARRIVAL_TIME" INT   NOT NULL,
    "ARRIVAL_DELAY" INT   NOT NULL,
    "DIVERTED" BOOLEAN   NOT NULL,
    "CANCELLED" BOOLEAN   NOT NULL,
    CONSTRAINT "pk_MODFLIGHTS" PRIMARY KEY (
        "FLIGHT_ID"
     )
);

ALTER TABLE "MODFLIGHTS" ADD CONSTRAINT "fk_MODFLIGHTS_AIRLINE_CODE" FOREIGN KEY("AIRLINE_CODE")
REFERENCES "AIRLINES" ("AIRLINE_CODE");

ALTER TABLE "MODFLIGHTS" ADD CONSTRAINT "fk_MODFLIGHTS_ORIGIN_AIRPORT_CODE" FOREIGN KEY("ORIGIN_AIRPORT_CODE")
REFERENCES "AIRPORTS" ("AIRPORT_CODE");

ALTER TABLE "MODFLIGHTS" ADD CONSTRAINT "fk_MODFLIGHTS_DESTINATION_AIRORT_CODE" FOREIGN KEY("DESTINATION_AIRORT_CODE")
REFERENCES "AIRPORTS" ("AIRPORT_CODE");

